// NOTE: This code is generated by LibTorchGenerator

// Ensure all TVM env are defined correctly Macros
#define DMLC_USE_LOGGING_LIBRARY <tvm/runtime/logging.h>

#include <tvm/runtime/logging.h>
#include <tvm/runtime/packed_func.h>
#include <tvm/runtime/ndarray.h>

#include <ATen/ATen.h>

namespace tvm_addon {
using namespace tvm;
using namespace tvm::runtime;

// simple specialized impl, can be replaced by
// call into libraries.
void AddOneCPU_(NDArray a, NDArray out) {
  CHECK_EQ(a->ndim, 1);
  CHECK_EQ(a->shape[0], out->shape[0]);
  CHECK_EQ(a.DataType(), DataType::Float(32));

  for (int i = 0; i < a->shape[0]; ++i) {
    static_cast<float*>(out->data)[i] = static_cast<float*>(a->data)[i] + 1;
  }
}

// export the implementation
TVM_DLL_EXPORT_TYPED_FUNC(ext_AddOneCPU, AddOneCPU_);
}
