// NOTE: This code is generated by LibTorchGenerator

// Ensure all TVM env are defined correctly Macros
#define DMLC_USE_LOGGING_LIBRARY <tvm/runtime/logging.h>

// #include <tvm/runtime/logging.h>
#include <tvm/runtime/packed_func.h>
#include <tvm/runtime/ndarray.h>

#include <ATen/ATen.h>
#include <ATen/DLConvertor.h>

namespace tvm_addon {
using namespace tvm;
using namespace tvm::runtime;

// simple specialized impl, can be replaced by
// call into libraries.
void AddCPU_(NDArray a, NDArray b, NDArray out) {
  DLManagedTensor* tensor;
  tensor = a.ToDLPack();
  at::Tensor a_torch = at::fromDLPack(tensor);

  tensor = b.ToDLPack();
  at::Tensor b_torch = at::fromDLPack(tensor);
  at::Tensor c = at::add(a_torch, b_torch);

  tensor = at::toDLPack(c);
  out = NDArray::FromDLPack(tensor);
}

// export the implementation
TVM_DLL_EXPORT_TYPED_FUNC(ext_AddCPU, AddCPU_);
}
